name: pyfirenze37
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - altair=4.0.1=py_0
  - asn1crypto=1.3.0=py37_0
  - astroid=2.3.3=py37_1
  - astropy=4.0=py37h516909a_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=1.4.0=py37_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - confuse=1.0.0=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - holoviews=1.12.7=py_0
  - htmlmin=0.1.12=py_1
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - importlib_metadata=1.3.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py37h39e3cac_1
  - ipython=7.11.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - lazy-object-proxy=1.4.3=py37h516909a_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm8=8.0.1=hc9558a2_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.31.0=py37h8b12597_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mccabe=0.6.1=py_1
  - missingno=0.4.2=py_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.2=py37_0
  - numba=0.47.0=py37hb3f55d8_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1=h7b6447c_0
  - packaging=20.0=py_0
  - pandas=0.25.3=py37he6710b0_0
  - pandas-profiling=2.4.0=py_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - panel=0.7.0=py_0
  - param=1.9.2=py_0
  - parso=0.5.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - phik=0.9.8=py_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.1=py_0
  - pycparser=2.19=py37_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.6=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - pytest=5.3.4=py37_0
  - pytest-pylint=0.14.1=py_0
  - pytest-runner=5.2=py_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.3=py_0
  - pyyaml=5.2=py37h7b6447c_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - scipy=1.3.2=py37h7c811a0_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py37_0
  - setuptools=44.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.11.0=py37h516909a_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h516909a_0
  - urllib3=1.25.7=py37_0
  - vega_datasets=0.8.0=py_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - pydataset==0.2.0
prefix: /home/jack/miniconda3/envs/pyfirenze37

